# Generated by Django 4.2.25 on 2025-11-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_assignmentsubmission_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gmail_permission_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gmail_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
