# Generated by Django 4.2.25 on 2025-11-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_gmail_permission_granted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gmail_privacy_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
