# Generated by Django 4.2.25 on 2025-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
